# -*- coding: utf-8 -*-
"""
Created on Mon Feb 21 11:01:21 2022

@author: eyu
"""

class NameToHeaderMap:
    scriptSimMap = {'totalFlow' : 'IKin__LowPassTotalFlowRate', 
                    'rightKneeFlow' : 'rightKneeLowPassFlowRate',
                    'leftKneeFlow' : 'leftKneeLowPassFlowRate',
                    'rightHipInnerFlow' : 'rightHipInnerLowPassFlowRate',
                    'leftHipInnerFlow' : 'leftHipInnerLowPassFlowRate',
                    'rightHipOuterFlow' : 'rightHipOuterLowPassFlowRate',
                    'leftHipOuterFlow' : 'leftHipOuterLowPassFlowRate',
                    'rightAnkleOuterFlow' : 'rightAnkleOuterLowPassFlowRate',
                    'leftAnkleOuterFlow' : 'leftAnkleOuterLowPassFlowRate',
                    'rightAnkleInnerFlow' : 'rightAnkleInnerLowPassFlowRate',
                    'leftAnkleInnerFlow' : 'leftAnkleInnerLowPassFlowRate',
                    'rightSpineFlow' : 'SpineOuterLowPassFlowRate',
                    'leftSpineFlow' : 'SpineInnerLowPassFlowRate',
                    'pelvisSpeedX' : 'qd_x',
                    'pelvisSpeedY' : 'qd_y',
                    'comSpeedX' : 'exactCenterOfMassVelocityX',
                    'comSpeedY' : 'exactCenterOfMassVelocityY',
                    'transferTime' : 'transferTime0',
                    'swingTime' : 'swingTime0',
                    'desiredSpeedX' : 'NA',
                    'desiredSpeedY' : 'NA',
                     'leftFootForceZ' : 'LEFT_FOOT_LINKFootForceMag',
                     'rightFootForceZ' : 'RIGHT_FOOT_LINKFootForceMag'}
    
    radioSimMap = {'totalFlow' : 'IKin__LowPassTotalFlowRate', 
                    'rightKneeFlow' : 'rightKneeLowPassFlowRate',
                    'leftKneeFlow' : 'leftKneeLowPassFlowRate',
                    'rightHipInnerFlow' : 'rightHipInnerLowPassFlowRate',
                    'leftHipInnerFlow' : 'leftHipInnerLowPassFlowRate',
                    'rightHipOuterFlow' : 'rightHipOuterLowPassFlowRate',
                    'leftHipOuterFlow' : 'leftHipOuterLowPassFlowRate',
                    'rightAnkleOuterFlow' : 'rightAnkleOuterLowPassFlowRate',
                    'leftAnkleOuterFlow' : 'leftAnkleOuterLowPassFlowRate',
                    'rightAnkleInnerFlow' : 'rightAnkleInnerLowPassFlowRate',
                    'leftAnkleInnerFlow' : 'leftAnkleInnerLowPassFlowRate',
                    'rightSpineFlow' : 'SpineOuterLowPassFlowRate',
                    'leftSpineFlow' : 'SpineInnerLowPassFlowRate',
                    'pelvisSpeedX' : 'qd_x',
                    'pelvisSpeedY' : 'qd_y',
                    'comSpeedX' : 'exactCenterOfMassVelocityX',
                    'comSpeedY' : 'exactCenterOfMassVelocityY',
                    'transferTime' : 'transferTimeCSG',
                    'swingTime' : 'swingTimeCSG',
                    'desiredSpeedX' : 'desiredVelocityCSGX',
                    'desiredSpeedY' : 'desiredVelocityCSGY',
                    'leftFootForceZ' : 'LEFT_FOOT_LINKFootForceMag',
                    'rightFootForceZ' : 'RIGHT_FOOT_LINKFootForceMag'}
    
    realMap = {'totalFlow' : 'Measured__LowPassTotalFlowRate', 
                'rightKneeFlow' : 'rightKneeISA_LowPassFlowRate',
                'leftKneeFlow' : 'leftKneeISA_LowPassFlowRate',
                'rightHipInnerFlow' : 'rightHipInnerISA_LowPassFlowRate',
                'leftHipInnerFlow' : 'leftHipInnerISA_LowPassFlowRate',
                'rightHipOuterFlow' : 'rightHipOuterISA_LowPassFlowRate',
                'leftHipOuterFlow' : 'leftHipOuterISA_LowPassFlowRate',
                'rightAnkleOuterFlow' : 'rightAnkleOuterISA_LowPassFlowRate',
                'leftAnkleOuterFlow' : 'leftAnkleOuterISA_LowPassFlowRate',
                'rightAnkleInnerFlow' : 'rightAnkleInnerISA_LowPassFlowRate',
                'leftAnkleInnerFlow' : 'leftAnkleInnerISA_LowPassFlowRate',
                'rightSpineFlow' : 'rightSpineISA_LowPassFlowRate',
                'leftSpineFlow' : 'leftSpineISA_LowPassFlowRate',
                'pelvisSpeedX' : 'qd_x', 
                'pelvisSpeedY' : 'qd_x',
                'comSpeedX' : 'predictedCoMVelocityX',
                'comSpeedY' : 'predictedCoMVelocityY',
                'swingTime' : 'swingTime0',
                'transferTime' : 'transferTime0',
                'leftFootForceZ' : 'LEFT_FOOT_LINKStateEstimatorForceZ',
                'rightFootForceZ' : 'RIGHT_FOOT_LINKStateEstimatorForceZ',
                'desiredSpeedX' : 'NA',
                'desiredSpeedY' : 'NA'} 